spring:
    rabbitmq:
        host: 192.168.87.1741111111
        port: 5672
        username: root
        password: thundersoft
        publisher-confirms: true	#  消息发送到交换机确认机制,是否确认回调
        queryMqStatusUrl: http://192.168.87.174:15672
        queryQueueCountUrl: http://192.168.87.174:15672/api/queues/%2F/second-queue
